Feature/contao4 refactoring
terminal42/contao-avatar pull request #14
Opened 2017-04-18 22:43 UTC by iCodr8

Es gab ein Paar Bugs in der Library, wenn man Contao 4.3 benutzt. Diese haben wir behoben. Ihr könnt diese gerne übernehmen.
Schaut euch einfach mal die Änderungen an.

2017-04-19 07:16 UTC, Toflar requested changes

2017-04-19 07:16 UTC, Toflar commented on forms/FormAvatar.php
> +                    $this->varValue = urldecode(\Image::get(
I know why you added this. This is because Contao - for whatever reason - encodes the path by default. But it uses `rawurlencode` so you should be using `rawurldecode` here :)

2017-04-19 07:16 UTC, Toflar commented on widgets/AvatarWidget.php
> +                    $this->varValue = urldecode(\Image::get(
Same here.

2017-04-19 07:16 UTC, Toflar commented on widgets/AvatarWidgetBase.php
> +            $strFileName = $_FILES[$strTempName]['name'];
Can you explain what you did here and why?

2017-04-19 07:16 UTC, Toflar commented on widgets/AvatarWidgetBase.php
> -        list($intWidth, $intHeight) = $this->getThumbnailDimensions($strFile);
I have no idea anymore what `getThumbnailDimensions()` did but why did you remove this?

2017-04-19 07:16 UTC, Toflar commented on widgets/AvatarWidgetBase.php
> -        \Image::resize($strFile, $intWidth, $intHeight, 'proportional');
Same question here: Why did you remove this?

2017-04-21 19:19 UTC, iCodr8 commented on forms/FormAvatar.php
> +                    $this->varValue = urldecode(\Image::get(
This is from hotfix/1.2.2.

2017-04-21 19:19 UTC, iCodr8 commented on widgets/AvatarWidget.php
> +                    $this->varValue = urldecode(\Image::get(
This is from hotfix/1.2.2.

2017-04-21 19:19 UTC, iCodr8 commented on widgets/AvatarWidgetBase.php
> -        list($intWidth, $intHeight) = $this->getThumbnailDimensions($strFile);
This is from hotfix/1.2.2.

2017-04-21 19:23 UTC, iCodr8 commented on widgets/AvatarWidgetBase.php
> +            $strFileName = $_FILES[$strTempName]['name'];
When you are uploading files that have spaces or multiple dots in the name, jcrop will not work. So I replaced spaces and dots (except the last one) with a "-".

2017-04-21 21:03 UTC, iCodr8 commented on widgets/AvatarWidgetBase.php
> -        \Image::resize($strFile, $intWidth, $intHeight, 'proportional');
This change was bullshit, I changed it back.

2017-04-23 14:51 UTC, Toflar commented on widgets/AvatarWidgetBase.php
> +            $strFileName = $_FILES[$strTempName]['name'];
Do you mind changing it to a simple regex then?
```php
$filename = preg_replace('/\.(?![^.]+$)|\s+/', '-', $_FILES[$strTempName]['name']);
```

Should do, no?

2021-09-06 14:46 UTC, closed without merging